# CC = GCC

# CFLAGS = -Wall -Wextra -Werror

# LIBS = -lreadline

# INCLUDES = ./includes/minishell.h

# NAME = minishell.a

# SOURCES = ./src/minishell.c

# OBJECTS = $(SOURCES:.c=.o)

# LIBFT_PATH = ./libft/

# all: subsystem $(NAME)

# info: header

# define HEADER

#         _                                    _ _ _       _                 _       _     _          _ _
#        | |                     ___          | | (_)     ( )               (_)     (_)   | |        | | |
#    __ _| | ___   _ _ __ ____  ( _ )     ___ | | |_  ___ |/ ___   _ __ ___  _ _ __  _ ___| |__   ___| | |
#   / _` | |/ / | | | '__|_  /  / _ \/\  / _ \| | | |/ _ \  / __| | '_ ` _ \| | '_ \| / __| '_ \ / _ \ | |
#  | (_| |   <| |_| | |   / /  | (_>  < | (_) | | | | (_) | \__ \ | | | | | | | | | | \__ \ | | |  __/ | |
#   \__,_|_|\_\\\__,_|_|  /___|  \___/\/  \___/|_|_|_|\___/  |___/ |_| |_| |_|_|_| |_|_|___/_| |_|\___|_|_|




# endef
# export HEADER

# header:
# 	@echo "$$HEADER"

# subsystem : header
# 	make -C ./libft
# 	cp ./libft/libft.a libft.a
+
# $(NAME): subsystem $(OBJECTS)
# 	$(CC) -c $(CFLAGS) $(LIBS) $(SOURCES)
# 	$(CC) $(CFLAGS) $(OBJECTS) $(SOURCES) -o minishell
# #add minishell.a before -o
# clean:
# 	rm -f $(OBJECTS)
# 	rm -f $(LIBFT_PATH)*.o

# fclean: clean
# 	rm -f $(NAME)
# 	rm -f $(LIBFT_PATH)libft.a
# 	rm -f libft.a
# 	rm -f minishell

# re: fclean all

